START_TIME = 'startTime'
LATENCY = 'latency'
NOT_AVAILABLE = 'N/A'

SERVER_HOST = 'serverHost'
SERVER_PORT = 'serverPort'

REQUEST = 'request'
REQUEST_ID = 'requestID'
REQUEST_REMOTE_IP = 'remoteIP'
REQUEST_REMOTE_PORT = 'remotePort'
REQUEST_PROTOCOL = 'protocol'
REQUEST_HOST = 'host'
REQUEST_METHOD = 'method'
REQUEST_URI = 'uri'
REQUEST_URI_PATH = 'uriPath'
REQUEST_ROUTE_PATH = 'routePath'
REQUEST_HTTP_REFERER = 'referer'
REQUEST_USER_AGENT = 'userAgent'
REQUEST_CONTENT_LENGTH = 'contentLength'
REQUEST_HEADERS = 'headers'
REQUEST_QUERY_PARAMS = 'queryParams'
REQUEST_BODY = 'requestBody'
RESPONSE = 'response'
RESPONSE_STATUS_CODE = 'status'
RESPONSE_ERROR = 'error'
RESPONSE_SIZE = 'responseSize'

SERVICE_NAME = 'serviceName'
APPLICATION_ID = 'applicationId'
ACTOR_ID = 'actorId'
ACTION_ID = 'actionId'
ACTION_DESCRIPTION = 'description'
